### PR TITLE
support HTTP

### PR DESCRIPTION
**Pull request by xtimon**

### CODE REVIEW

**Comment by pschmitt** [comment]
So people are still using http in 2018. Okay, I get the need but would you mind adding a check for the `method` argument so that it raises an exception when set so something not supported - such as `ftp`? I'll merge it then.

**Comment by xtimon** [comment]
> So people are still using http in 2018.

I needed `http` to be able to connect to a test installation of Guacamole. I would change this setting to `url` but I didn't want to broke compatibility.

> PS: Why did you add simplejson as a requirement?

`simplejson` is not included to Python by default, but you use it in  [code](https://github.com/pschmitt/guacapy/blob/master/guacapy/client.py#L6)

**Comment by pschmitt** [comment]
You are right for the `simplejson` dependency.

But what I requested was a simple check on the new parameter you are introducing. Something along the lines of:

```
if method.lower() not in ["https", "http"]:
  raise WrongMethodException("Only HTTP and HTTPS are supported")
```

**Comment by pschmitt** [comment]
uh okay.

I ended up doing this myself in 06ee69882ada40870694c2cd223b712802966f82 and 0d15ee44429cfffff685b901473f5e5404efbb3e

**Pull request closed without merging**
