### PR TITLE
disable "json_response" for several edition/deletion calls

### PR DESCRIPTION
**Pull request by toutoen**

### CODE REVIEW

**Comment by pschmitt** [comment]
I currently don't have access to guacamole. Why is this necessary? Isnt the response json here as well? Can you maybe provide a snippet which highlights the issue you are attempting to fix here? Thanks!

**Comment by toutoen** [comment]
You're right, I could have provided a snippet :)

```
In [1]: guacapy.Guacamole(**params)
[...]
In [1]: client.delete_connection_group(61)
ERROR:guacapy.client:Could not decode JSON response
Out[1]: <Response [204]>
```
Since this deletion provides a `No-content` HTTP server response, there's no JSON to analyze and no reason to log an error.

**Comment by toutoen** [comment]
Any news,  @pschmitt ? :)

**Comment by pschmitt** [comment]
Hehe good that you pinged me, merging!

**Comment by toutoen** [comment]
Thanks btw!
Would you release a new version as well?

**Comment by pschmitt** [comment]
Took me a while but here you go:
https://pypi.org/project/guacapy/0.11.1/

**Pull request merged**
